# syntax=docker/dockerfile:1
FROM golang:1.26-alpine@sha256:91eda9776261207ea25fd06b5b7fed8d397dd2c0a283e77f2ab6e91bfa71079d AS builder
WORKDIR /app
COPY . .
ARG UI_OVERLAY=""
RUN if [ -n "$UI_OVERLAY" ]; then cp -r overlays/$UI_OVERLAY/* ui/; fi
RUN CGO_ENABLED=0 go build -o /agent-bin ./cmd/agent

FROM gcr.io/distroless/static-debian12@sha256:9c346e4be81b5ca7ff31a0d89eaeade58b0f95cfd3baed1f36083ddb47ca3160
COPY --from=builder /agent-bin /agent
ENTRYPOINT ["/agent"]
