name: OpenSSF Scorecard

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '30 1 * * 0'

permissions:
  contents: read

jobs:
  scorecard:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Run OpenSSF Scorecard analysis
        uses: ossf/scorecard-action@3d34671c90ff84e8b851ad4de5ca3dc589cbad79 # v2.3.0
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Scorecard results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@fee9466b8957867761f2d78f922ab084e3e2dd17 # v3
        with:
          sarif_file: results.sarif
